#.travis.yml

language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng lint
  - ng test
  - npm run packagr

deploy:
  provider: npm
  email: johnny@johnfedoruk.ca
  api_key: $NPM_TOKEN
  on:
    - tags: true
    - branch: master

notifications:
  email:
    on_failure: change
    on_success: change
